[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/Library/Frameworks/Python.framework/Versions/3.9/lib",
  "-C", "link-arg=-lpython3.9",
  "-C", "link-arg=-Wl,-rpath,/Library/Frameworks/Python.framework/Versions/3.9/lib",
  "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks",
  "-C", "link-arg=-Wl,-rpath,/usr/lib"
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/Library/Frameworks/Python.framework/Versions/3.9/lib",
  "-C", "link-arg=-lpython3.9",
  "-C", "link-arg=-Wl,-rpath,/Library/Frameworks/Python.framework/Versions/3.9/lib",
  "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks",
  "-C", "link-arg=-Wl,-rpath,/usr/lib"
]
